server:
  port: 8082

zeebe:
  client:
    cloud:
      cluster-id: ${ZEEBE_CLUSTER_ID}
      client-secret: ${ZEEBE_CLIENT_SECRET}
      client-id: ${ZEEBE_CLIENT_ID}
      region: ${ZEEBE_CLIENT_REGION}

seller:
  mail-address: ${SELLER_MAIL_ADDRESS}
# You can also configure the connection to a self-managed Zeebe broker:
#    broker:
#      gateway-address: 127.0.0.1:26500
#    security:
#      plaintext: 'true'