server:
  port: 8083
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_ACCESS_PASSWORD}
    port: 587

